sudo: false
branches:
  except: /^v\d/
language: node_js
node_js:
  - stable
  - '0'
  - '0.10'
after_script:
  - npm install istanbul-coveralls@1
  - npm run-script coverage
  - node node_modules/.bin/istanbul-coveralls
